### ISSUE TITLE
elaborate on the install progress

### ISSUE THREAD

**Issue by sanderhouttekier** [edipox/n1-ido#33]
1. i was using mailspring already, so i skipped this
2. I downloaded the master branch, that zip file is sitting in my downloads folder
3. I opened that 'install new theme...' dialog. and now i'm drinking that coffee i was going to buy you, all by myself. because i'm stuck there.

/sarcasm aside, could you just elaborate on the install process so dummies like me know what to do as well? 

for starters:  you cannot install a zip file, so mention the need to extract it.
secondly: should you install it from the extracted folder in your download directory or not...
does it copy the theme and move it somewhere or will it just reference the downloaded folder
as in, can i then delete the files in my download folder or will the theme and mailspring then get stuck?

honestly, i have to give it to you, you did go out of your way to document your theme, or the way to change a background colour of the sidebar. Yet you somehow thought the install section would be enough with 3 steps leaving us hanging halfway the process :)

**Comment by edipox** [comment]
@saelfaer thanks for reporting. I think the download process changed with the new version of `Mailspring`, so now instead of selecting the `zip` file you need to decompress the zip and then select the folder. I'll update the documentation in order to clarify this, but I don't recommend you to use this theme right now, since I also discovered some compatibility issues with the theme and the new version of `Mailspring`. I created this issue https://github.com/edipox/n1-ido/issues/34 where we'll handle the fix
